export const LIST_FETCH_SUCCESS = 'LIST_FETCH_SUCCESS';
export const GET_ERROR = 'GET_ERROR';
export const SELECT_ITEM = 'SELECT_ITEM';
export const DESELECT_ITEM = 'DESELECT_ITEM';
export const SHOW_LOADER = 'SHOW_LOADER';